export const albumsList = [
  {
    vid: 1,
    artist: "King Crimson",
    genre: "Rock",
    price: 30,
    name: "In the Court of the Crimson King",
    releaseYear: 1969,
  },
  {
    vid: 2,
    artist: "Pink Floyd",
    genre: "Rock",
    price: 25,
    name: "The Dark Side of the Moon",
    releaseYear: 1973,
  },
  {
    vid: 3,
    artist: "Pink Floyd",
    genre: "Rock",
    price: 25,
    name: "The Wall",
    releaseYear: 1979,
  },
  {
    vid: 4,
    artist: "Creedence Clearwater Revival",
    genre: "Rock",
    price: 28,
    name: "Cosmos Factory",
    releaseYear: 1970,
  },
  {
    vid: 5,
    artist: "Creedence Clearwater Revival",
    genre: "Rock",
    price: 26,
    name: "Pendulum",
    releaseYear: 1970,
  },
  {
    vid: 6,
    artist: "The Beatles",
    genre: "Rock",
    price: 35,
    name: "Revolver",
    "release year": 1966,
  },
  {
    vid: 7,
    artist: "The Beatles",
    genre: "Rock",
    price: 35,
    name: "Abbey Road",
    releaseYear: 1969,
  },
  {
    vid: 8,
    artist: "Iron Maiden",
    genre: "Metal",
    price: 32,
    name: "Powerslave",
    releaseYear: 1984,
  },
  {
    vid: 9,
    artist: "Iron Maiden",
    genre: "Metal",
    price: 29,
    name: "Iron Maiden",
    releaseYear: 1980,
  },
  {
    vid: 10,
    artist: "System of a Down",
    genre: "Metal",
    price: 31,
    name: "Steal This Album",
    releaseYear: 2003,
  },
  {
    vid: 11,
    artist: "System of a Down",
    genre: "Metal",
    price: 33,
    name: "Mezmerize",
    releaseYear: 2005,
  },
  {
    vid: 12,
    artist: "Limp Bizkit",
    genre: "Metal",
    price: 32,
    name: "Significant Other",
    releaseYear: 1999,
  },
  {
    vid: 13,
    artist: "Metallica",
    genre: "Metal",
    price: 55,
    name: "Hardwired... to Self-Destruct",
    releaseYear: 2016,
  },
  {
    vid: 14,
    artist: "Avenged Sevenfold",
    genre: "Metal",
    price: 40,
    name: "Life is But a Dream...",
    releaseYear: 2023,
  },
  {
    vid: 15,
    artist: "Taylor Swift",
    genre: "Pop",
    price: 40,
    name: "1989 (Taylor Swift Version)",
    releaseYear: 2023,
  },
  {
    vid: 16,
    artist: "Miley Cyrus",
    genre: "Pop",
    price: 45,
    name: "Endless Summer Vacation",
    releaseYear: 2023,
  },
  {
    vid: 17,
    artist: "Michael Jackson",
    genre: "Pop",
    price: 33,
    name: "Thiller",
    releaseYear: 1982,
  },
  {
    vid: 18,
    artist: "Pet Shop Boys",
    genre: "Pop",
    price: 28,
    name: "Please",
    releaseYear: 1986,
  },
  {
    vid: 19,
    artist: "Jon Batiste",
    genre: "Pop",
    price: 40,
    name: "World Radio Music",
    releaseYear: 2023,
  },
];
